Notifications: {
    shape: sql_table
    id: string {constraint: primary_key}
    __typename: Notification
    _lastChangedAt: int
    _version: int
    message: string
    timestamp: int
    title: string
    updatedAt: string
    userId: string
  }
  