
name: Deploy Stream Input

on: 
  push:
    paths:
      - infraestructure/streams/input/*
  workflow_dispatch:

        

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2 
        with:
          audience: 'sts.amazonaws.com'
          aws-region: 'eu-west-1'
          # aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-session-name: GitHubActions
          role-to-assume: ${{ secrets.AWS_GITHUB_ROUTE53_ROLE }}
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
  
      - name: Install CDK
        uses: pepitoenpeligro/setup-cdk@v1

      - name: Install CDK dependencies 
        working-directory: infrastructure/streams/input 
        run: 
          npm install

      - name: CDK deploy
        working-directory: infrastructure/streams/input  
        run: |
          ls -la
          cdk deploy --require-approval never -vv